Repository CS2103-AY1819S2-W14-3/main, pull requests merged in 2019-03, with the labels that each got.

#58 Add battle component
  src/main/java/seedu/address/logic/commands/AttackCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AttackCommandParser.java
  src/test/java/seedu/address/logic/parser/AttackCommandParserTest.java
Labels: enhancement

#189 Add support for tagging battleships
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListTagsCommand.java
  src/main/java/seedu/address/logic/commands/PutShipCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PutShipCommandParser.java
  src/main/java/seedu/address/model/MapGrid.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/battleship/AircraftCarrierBattleship.java
  src/main/java/seedu/address/model/battleship/Battleship.java
  src/main/java/seedu/address/model/battleship/CruiserBattleship.java
  src/main/java/seedu/address/model/battleship/DestroyerBattleship.java
  src/main/java/seedu/address/model/player/Fleet.java
  src/test/java/seedu/address/logic/commands/ListTagsCommandTest.java
  src/test/java/seedu/address/logic/commands/PutShipCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/PutShipCommandParserTest.java
  src/test/java/seedu/address/model/BoundaryValueCheckerTest.java
  src/test/java/seedu/address/model/MapGridTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/battleship/BattleshipTest.java
  src/test/java/seedu/address/model/player/FleetTest.java
Labels: status.Ongoing

#193 Update ListCommand to support tagging
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PutShipCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/cell/Coordinates.java
  src/main/java/seedu/address/model/player/Fleet.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: priority.High

#202 Minor fixes to Cell and MapGrid
  src/main/java/seedu/address/model/MapGrid.java
  src/main/java/seedu/address/model/cell/Cell.java
Labels: status.Ongoing

#203 Map UG documentation
  docs/UserGuide.adoc
  docs/diagrams/Map legends.pptx
  docs/images/initmap.PNG
  docs/images/initmapresult.png
  docs/images/maplegend.PNG
Labels: status.Ongoing

#224 Add sequence diagrams and logging, and refactor code
  docs/DeveloperGuide.adoc
  docs/diagrams/ListShipSequenceDiagram.pptx
  docs/diagrams/ListTagsSequenceDiagram.pptx
  docs/diagrams/PutShipSequenceDiagram.pptx
  docs/images/ListShipSequenceDiagram.png
  docs/images/ListTagsSequenceDiagram.png
  docs/images/PutShipSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PutShipCommand.java
  src/main/java/seedu/address/model/battleship/Battleship.java
  src/main/java/seedu/address/model/battleship/Orientation.java
  src/main/java/seedu/address/model/cell/Coordinates.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.High, status.Ongoing
