Repository CS2103-AY1819S2-W14-3/main, pull requests merged in 2019-04, with the labels that each got.

#271 Fix duplicate attacking in Enemy
  src/main/java/seedu/address/model/player/Enemy.java
Labels: type.Bug

#282 Fix bug for duplicate attacking in Enemy
  src/main/java/seedu/address/model/player/Enemy.java
Labels: type.Bug

#284 Lucy1.4
  src/main/java/seedu/address/logic/battle/AttackResult.java
  src/main/java/seedu/address/logic/commands/EndTurnCommand.java
  src/main/java/seedu/address/model/player/Enemy.java
Labels: type.Bug

#288 Modify result string for attacks.
  src/main/java/seedu/address/logic/battle/AttackDestroyedShip.java
  src/main/java/seedu/address/logic/battle/AttackFailed.java
  src/main/java/seedu/address/logic/battle/AttackHit.java
  src/main/java/seedu/address/logic/battle/AttackMissed.java
  src/main/java/seedu/address/logic/battle/AttackResult.java
  src/main/java/seedu/address/logic/battle/BattleManager.java
  src/main/java/seedu/address/logic/commands/AttackCommand.java
Labels: type.Enhancement

#281 Documentation updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/BattleshipModelDiagram.pptx
  docs/diagrams/InitialiseMapSequenceDiagram.pptx
  docs/diagrams/ListShipSequenceDiagram.pptx
  docs/diagrams/PutShipSequenceDiagram.pptx
  docs/images/InitialiseMapCommandSequenceDiagram.png
  docs/images/ListShipSequenceDiagram.png
  docs/images/PutShipSequenceDiagram.png
  src/main/java/seedu/address/logic/battle/BattleManager.java
Labels: status.Ongoing

#303 Lucy fix enemy shoot parity bug
  src/main/java/seedu/address/model/player/Enemy.java
Labels: type.Bug

#306 Documentation 1.4
  docs/UserGuide.adoc
  src/main/resources/view/MainWindow.fxml
Labels: Documentation

#338 Remove AB4 codebase
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/MapGrid.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/cell/Cell.java
  src/main/java/seedu/address/model/cell/Row.java
  src/main/java/seedu/address/model/cell/exceptions/BattleshipNotPresentException.java
  src/main/java/seedu/address/model/cell/exceptions/DuplicatePersonException.java
  src/main/java/seedu/address/model/cell/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/model/MapGridTest.java
  src/test/java/seedu/address/model/cell/CellTest.java
  src/test/java/seedu/address/model/cell/UniqueCellListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCellTest.java
  src/test/java/seedu/address/storage/JsonMapGridStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableMapGridTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/SizeTenMapGrid.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: status.Ongoing

#354 Change order of enemy shooting for cardinal cells
  src/main/java/seedu/address/model/player/Enemy.java
Labels: priority.Medium, type.Task

#356 Update enemy algo
  docs/team/bostoncheong.adoc
  src/main/java/seedu/address/model/player/Enemy.java
Labels: type.Bug

#362 Updated PPP
  docs/images/bos10.png
  docs/team/bostoncheong.adoc
Labels: Documentation

#379 Create Statistics Related Tests (Coveralls are ROCKETTING UP BOIS)
  docs/diagrams/SaveSequenceDiagram.pptx
  docs/diagrams/StatsSequenceDiagram.pptx
  docs/images/SaveSequenceDiag.PNG
  docs/team/bostoncheong.adoc
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/model/ReadOnlyStatisticsData.java
  src/main/java/seedu/address/storage/JsonStatisticsStorage.java
  src/test/data/JsonSerializableStatistics/statsTest.json
  src/test/data/JsonSerializableStatistics/statsTest2.json
  src/test/data/JsonSerializableStatistics/statsTest3.json
  src/test/data/JsonSerializableStatistics/statsTeststatsCommand.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/StatisticsTest.java
  src/test/java/seedu/address/logic/commands/SaveCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
  src/test/java/seedu/address/testutil/SerializableTestClass.java
Labels: Documentation, status.Ongoing

#393 Make minor improvements to documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ListTagsSdForLogic.pptx
  docs/images/DeletePersonSdForLogic.png
  docs/images/ListTagsSdForLogic.png
Labels: Documentation

#395 Documentation v1.4
  docs/DeveloperGuide.adoc
Labels: Documentation, status.Ongoing

#375 Enemy tests
  src/main/java/seedu/address/model/player/Enemy.java
  src/test/java/seedu/address/model/player/EnemyTest.java
  src/test/java/seedu/address/testutil/SizeTenMapGrid.java
Labels: priority.High, status.Ongoing, tests

#399 Boston-Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ReadSequenceDiagram.pptx
  docs/diagrams/SaveSequenceDiagram.pptx
  docs/diagrams/StatisticsActivityDiagram.pptx
  docs/diagrams/StatsSequenceDiagram.pptx
  docs/diagrams/StatsUseCaseDiagram.pptx
  docs/images/ReadSequenceDiagram.PNG
  docs/images/SaveSequenceDiag.PNG
  docs/images/SaveSequenceDiagram.png
  docs/images/StatisticsActivityDiagram.png
  docs/images/StatsSequenceDiagram.PNG
  docs/images/StatsUseCaseDiag.PNG
  docs/team/bos10.adoc
  src/main/java/seedu/address/logic/commands/SaveCommand.java
Labels: Documentation, status.Ongoing

#405 Enemy java docs
  src/main/java/seedu/address/model/player/Enemy.java
  src/main/java/seedu/address/model/player/Player.java
Labels: Documentation, severity.Medium
